// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtbSEctvbdpkx42tzdtQahqVcKitIgyQ',
    appId: '1:740291312737:web:ffcc4bc14d587639413e20',
    messagingSenderId: '740291312737',
    projectId: 'nutrition-app-e051c',
    authDomain: 'nutrition-app-e051c.firebaseapp.com',
    storageBucket: 'nutrition-app-e051c.firebasestorage.app',
    measurementId: 'G-83TEPGKCP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJNLBuBx3mD8Px0a7yADtNivYCVyGCdw',
    appId: '1:740291312737:android:fba082a75fe1a5ab413e20',
    messagingSenderId: '740291312737',
    projectId: 'nutrition-app-e051c',
    storageBucket: 'nutrition-app-e051c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tIDVyJDIUyAkJL6cEwSro1s-lznCRVw',
    appId: '1:740291312737:ios:d60c0338ea499cb8413e20',
    messagingSenderId: '740291312737',
    projectId: 'nutrition-app-e051c',
    storageBucket: 'nutrition-app-e051c.firebasestorage.app',
    iosBundleId: 'com.example.nuttritionapp',
  );
}
